
env: "local" # local dev prod
storage_type: "postgres"  # memory postgres
storage_path: "host=postgres port=5432 user=postgres password=mysecretpassword dbname=postgres sslmode=disable"
http_server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 60s